apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
  namespace: nginx
data:
  config.hcl: |
    listen {
      port = 4040
    }

    namespace "nginx" {
      print_log = true
      source = {
        files = [
          "/mnt/nginxlog/access.log"
        ]
      }

      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
      relabel "resource" { 
        from = "request" 
        split = 2
        match "^/v1/([a-z_]*)[?/].*$" {
          replacement = "$1"
        }
      }
      relabel "user_agent" { 
        from = "http_user_agent" 
      }
      labels {
        app = "default"
      }
    }
