persistence:
  enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: g.monitoring.23t-prod.okeanos.dev
    dns.gardener.cloud/ttl: "500"
  tls:
    - secretName: grafana-tls
      hosts:
        - g.monitoring.23t-prod.okeanos.dev
  hosts:
    - g.monitoring.23t-prod.okeanos.dev
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      isDefault: true
grafana.ini:
  auth.anonymous:
    enabled: true
