controller:
  extraContainers:
    - name: exporter
      image: ghcr.io/martin-helmich/prometheus-nginxlog-exporter/exporter:v1
      args: ["-config-file", "/etc/prometheus-nginxlog-exporter/config.hcl"]
      volumeMounts:
        - name: exporter-config
          mountPath: /etc/prometheus-nginxlog-exporter
        - name: nginxlog
          mountPath: /mnt/nginxlog
  extraInitContainers:
    - name: fix-permissions
      image: docker.io/alpine:3.17.0
      command:
        - chown
        - -R
        - 101:101
        - /mnt/nginxlog
      volumeMounts:
        - name: nginxlog
          mountPath: /mnt/nginxlog
  extraVolumes:
    - name: exporter-config
      configMap:
        name: exporter-config
    - name: nginxlog
      persistentVolumeClaim:
        claimName: nginx-access-log
  extraVolumeMounts:
    - name: nginxlog
      mountPath: /mnt/nginxlog
