apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy
  name: deploy
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - command:
            - sleep
            - "3600"
          image: busybox
          name: busybox
